# Generated by Django 3.0.3 on 2020-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dcm',
            field=models.FileField(default='photos/no_image.png', upload_to='./photos'),
        ),
    ]
