# Generated by Django 3.0.3 on 2020-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_dcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='files',
            field=models.FilePathField(default='./photos'),
        ),
    ]
