# Generated by Django 3.0.3 on 2020-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='files',
            field=models.FilePathField(path='photo/'),
        ),
    ]
