# Generated by Django 3.0.3 on 2020-06-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200625_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dcm',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='files',
        ),
    ]
