# Generated by Django 3.0.3 on 2020-06-28 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0005_auto_20200625_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_photo', models.ImageField(default='photos/no_image.png', upload_to='./photos')),
                ('test_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
