# Generated by Django 3.0.3 on 2020-06-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
